CREATE DATABASE Cyberthreat_Intelligence;
USE Cyberthreat_Intelligence;
DROP DATABASE Cyberthreat_Intelligence;

CREATE DATABASE Cyberthreat_Intelligence;
USE Cyberthreat_Intelligence;

CREATE TABLE ATTACK_TYPE (
    ATTACK_TYPE_ID VARCHAR(20) NOT NULL,
    TYPE_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT ATTACK_TYPE_PK PRIMARY KEY (ATTACK_TYPE_ID));
    
	CREATE TABLE ORGANIZATION (
    ORG_ID VARCHAR(20) NOT NULL,
    ORG_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100),
    CONSTRAINT ORGANIZATION_PK PRIMARY KEY (ORG_ID));
    
    CREATE TABLE THREAT (
    THREAT_ID INT NOT NULL,
    THREAT_NAME VARCHAR(100) NOT NULL,
    SEVERITY_LEVEL VARCHAR(20),
    DATE_OCCURRED DATE,
    ATTACK_TYPE_ID VARCHAR(20),
    CONSTRAINT THREAT_PK PRIMARY KEY (THREAT_ID),
    CONSTRAINT THREAT_FK_ATTACK_TYPE FOREIGN KEY (ATTACK_TYPE_ID) REFERENCES ATTACK_TYPE(ATTACK_TYPE_ID));
    
    CREATE TABLE INCIDENT_RESPONSE_TEAM (
    TEAM_ID VARCHAR(20) NOT NULL,
    TEAM_NAME VARCHAR(100) NOT NULL,
    CONTACT_INFO VARCHAR(100),
    CONSTRAINT INCIDENT_RESPONSE_TEAM_PK PRIMARY KEY (TEAM_ID));
    
    CREATE TABLE THREAT_SOURCE (
    SOURCE_ID VARCHAR(20) NOT NULL,
    SOURCE_TYPE VARCHAR(50) NOT NULL,
    SOURCE_DESCRIPTION TEXT,
    CONSTRAINT THREAT_SOURCE_PK PRIMARY KEY (SOURCE_ID));
    
    CREATE TABLE MITIGATION_ACTION (
    MITIGATION_ID VARCHAR(20) NOT NULL,
    ACTION_DESCRIPTION VARCHAR(255) NOT NULL,
    DATE_IMPLEMENTED DATE,
    CONSTRAINT MITIGATION_ACTION_PK PRIMARY KEY (MITIGATION_ID));
    
    CREATE TABLE THREAT_IMPACT (
    THREAT_ID INT,
    ORG_ID VARCHAR(20),
    IMPACT_LEVEL VARCHAR(50),
    IMPACT_DATE DATE,
    PRIMARY KEY (THREAT_ID, ORG_ID),
    FOREIGN KEY (THREAT_ID) REFERENCES THREAT(THREAT_ID),
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID));
    
    CREATE TABLE THREAT_MITIGATION (
    THREAT_ID INT NOT NULL,
    MITIGATION_ID VARCHAR(20) NOT NULL,
    MITIGATION_STATUS VARCHAR(50),
    REVIEW_DATE DATE,
    CONSTRAINT THREAT_MITIGATION_PK PRIMARY KEY (THREAT_ID, MITIGATION_ID),
    CONSTRAINT THREAT_MITIGATION_FK_THREAT FOREIGN KEY (THREAT_ID) REFERENCES THREAT(THREAT_ID),
    CONSTRAINT THREAT_MITIGATION_FK_MITIGATION FOREIGN KEY (MITIGATION_ID) REFERENCES MITIGATION_ACTION(MITIGATION_ID));

    
    



    
    

    




